# Generated by Django 4.0.5 on 2022-06-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pravotznpk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Question',
        ),
    ]
